//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class game_shop_webEntities : DbContext
    {
        public game_shop_webEntities()
            : base("name=game_shop_webEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<banner> banners { get; set; }
        public virtual DbSet<blog> blogs { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<product_img_url> product_img_url { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<order_product> order_product { get; set; }
    }
}
